# Joint Probability

In [2]:
%matplotlib inline
import numpy as np

In [44]:
P=np.array([[2.,2,4],[1,1,2]])
P2 = np.array([[3.,4,5],[4,3,3]])

In [14]:
s = 0
for i in range(shape(P)[0]):
    for j in range(shape(P)[1]):
        s += P[i,j]
print('the sum is ',s)
#divide by the sum
for i in range(shape(P)[0]):
    for j in range(shape(P)[1]):
        P[i,j] /= s
P

the sum is  12.0


array([[0.16666667, 0.16666667, 0.33333333],
       [0.08333333, 0.08333333, 0.16666667]])

In [15]:
# Using Numpy we can write it in a much shorter way
P2 /= sum(P2)
P2

array([[0.13636364, 0.18181818, 0.22727273],
       [0.18181818, 0.13636364, 0.13636364]])

In [20]:
# The values that the random variables x and y take
x=np.array([2,3,6])
y=np.array([-1,1])

# Marginal Probabilities

In [46]:
# The pure python way
Px=[0.]*shape(P)[1]
Py=[0.]*shape(P)[0]

for i in range(len(Px)):
    for j in range(len(Py)):
        Px[i]+=P[j,i]
        Py[j]+=P[j,i]
Px,Py

([3.0, 3.0, 6.0], [8.0, 4.0])

In [24]:
#the numpy way:
Px=sum(P,axis=0)
Py=sum(P,axis=1)
Px,Py

(array([0.25, 0.25, 0.5 ]), array([0.66666667, 0.33333333]))

# Check for independence

If they are independent then the outer product and P should be equal

In [25]:
# The pure python way
for i in range(len(Px)):
    for j in range(len(Py)):
        if Px[i]*Py[j] != P[j,i]:
            print("Px[%d]*Py[%d] != P[%d,%d] ::::: %5.3f*%5.3f = %5.3f != %5.3f"%(i,j,j,i,Px[i],Py[j],Px[i]*Py[j],P[j,i]))

In [26]:
# The numpy way
np.outer(Px,Py).T - P

array([[0., 0., 0.],
       [0., 0., 0.]])

# Functions

In [29]:
P = [8, 9, 8, 9, 9, 2, 3, 7]

In [31]:
def Sq_list(list1):
    return np.array(list1)**2

In [32]:
Sq_list(P)

array([64, 81, 64, 81, 81,  4,  9, 49], dtype=int32)

In [33]:
sum(P)

55

In [34]:
def Var(list1):
    mean = sum(P)/len(P)
    deviation = [(x - mean)**2 for x in list1]
    variance = sum(deviation)/len(P)
    return variance

In [35]:
Var(P)

6.859375

In [36]:
def SQRoot(list1):
    mean = sum(P)/len(P)
    deviation = [(x - mean)**2 for x in list1]
    variance = sum(deviation)/len(P)
    Sqr = sqrt(variance)
    return Sqr

In [37]:
SQRoot(P)

2.6190408549696205

In [41]:
import statistics
def skewness(list1):
    skewness = (statistics.mean(list1) - statistics.mode(list1))/statistics.stdev(list1)
    return skewness

In [42]:
skewness(P)

-0.7589631459745645